version: '3.8'

services:
  vpn-server:
    build: .
    container_name: my-vpn-server
    privileged: true
    network_mode: "host"
    restart: always
    volumes:
      - /lib/modules:/lib/modules
